force-publish:
	@npm publish auth-persona -f
	@npm publish auth-simple -f
	@npm publish components -f
	@npm publish data-memory -f
	@npm publish data-postgres -f
	@npm publish data -f
	@npm publish errors -f
	@npm publish files -f
	@npm publish functions -f
	@npm publish helpers-frontend -f
	@npm publish jungles -f
	@npm publish middleware-frontend -f
	@npm publish middleware-general -f
	@npm publish panel -f
	@npm publish rest -f
	@npm publish types -f
	@npm publish validation -f
	@npm publish validators -f
