symlink:
	@ln -s ../../auth-persona node_modules/jungles-auth-persona
	@ln -s ../../auth-simple node_modules/jungles-auth-simple
	@ln -s ../../data-postgres node_modules/jungles-data-postgres
	@ln -s ../../data-memory node_modules/jungles-data-memory
	@ln -s ../../rest node_modules/jungles-rest
	@ln -s ../../panel node_modules/jungles-panel
	@ln -s ../../files node_modules/jungles-files
	@ln -s ../../helpers-frontend node_modules/jungles-helpers-frontend
	@ln -s ../../middleware-frontend node_modules/jungles-middleware-frontend
	@ln -s ../../errors node_modules/jungles-errors
	@ln -s ../../validation node_modules/jungles-validation
	@ln -s ../../validators node_modules/jungles-validators
	@ln -s ../../components node_modules/jungles-components
	@ln -s ../../functions node_modules/jungles-functions
	@ln -s ../../middleware-general node_modules/jungles-middleware-general
	@ln -s ../../types node_modules/jungles-types
